# Generated by Django 4.2.6 on 2023-10-07 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('video', models.CharField(max_length=250, verbose_name='Видео')),
                ('length_video', models.IntegerField(verbose_name='Длительность видео')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('author', models.BooleanField(default=False, verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='ProductUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.users')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='access',
            field=models.ManyToManyField(related_name='user_access', through='lessons.ProductUsers', to='lessons.users'),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.users'),
        ),
        migrations.AddField(
            model_name='product',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
        migrations.CreateModel(
            name='LessonUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewing_time', models.IntegerField(verbose_name='Длительность просмотра')),
                ('viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.users')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='viewing',
            field=models.ManyToManyField(related_name='viewing_user', through='lessons.LessonUsers', to='lessons.users'),
        ),
    ]
